### ISSUE TITLE
Used code for an angular pipe.

### ISSUE THREAD

**Issue by queejie** [jperkin/chordpro.js#1]
Hi Jonathan,

Just wanted to let you know that I used this code as a starter for [ngx-chordpro-pipe](https://github.com/queejie/ngx-chordpro-pipe).  It is in typescript, but it includes transposing and some minimal directive handling, in case you wanted to add it here.

Thanks, and best regards,
-dqj

**Comment by jperkin** [comment]
Good to know, thanks!
